import WritePage from '../Add-blog/WritePage'
import Navbar from '../Navbar/Navbar'
import Hero from './Hero'






export default function Home() {
  return (
    <div>
      <Navbar></Navbar>
      <Hero></Hero>

      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non animi repellat praesentium officiis numquam consequuntur eveniet, repudiandae ipsum tempora assumenda ipsa, voluptatem maiores obcaecati facere perspiciatis exercitationem in atque magni ab alias fugit? Eum quibusdam, velit excepturi, atque mollitia exercitationem possimus vero neque, reprehenderit cum natus vitae praesentium. Natus obcaecati dolorum magni atque doloremque, commodi deleniti fugit vero voluptatem unde odio totam fuga aspernatur velit reiciendis maiores distinctio, nesciunt iure qui dicta! In mollitia ipsum amet sunt, quam vitae pariatur. Eaque quia id tempora. Facere eaque veritatis quas sequi ea beatae minus ducimus, quam aut ipsum at, nihil suscipit tenetur?</p>
    <WritePage></WritePage>
    </div>
  )
}
